# Generated by Django 3.2.11 on 2022-11-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20221107_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
