# Generated by Django 3.2.11 on 2022-12-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20221109_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.AddField(
            model_name='customuser',
            name='establishment',
            field=models.CharField(choices=[('HOS', 'Hospital'), ('CLHE', 'Clinic/Health Centre'), ('PHM', 'Pharmacy'), ('CHSU', 'Chemist/Superstore')], default='pha', max_length=7),
            preserve_default=False,
        ),
    ]
