# Generated by Django 3.2.11 on 2022-12-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20221211_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='establishment',
        ),
    ]
