# Generated by Django 3.2.11 on 2022-12-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_remove_customuser_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='establishment',
            field=models.CharField(choices=[('HOS', 'Hospital'), ('CLHE', 'Clinic/Health Centre'), ('PHM', 'Pharmacy'), ('CHSU', 'Chemist/Superstore')], default='PHM', max_length=7),
            preserve_default=False,
        ),
    ]
