export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const USER_LOADED = "USER_LOADED"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const BRANDS_RETRIEVED = "BRANDS_RETRIEVED"
export const ORDER_CREATED = "ORDER_CREATED"
export const CHANGE_CREATED_FALSE = "CHANGE_CREATED_FALSE"
export const LAST_ORDER_FETCHED = "LAST_ORDER_FETCHED"
export const ORDER_PRODUCT_CREATED = "ORDER_PRODUCT_CREATED"


