# Generated by Django 3.2.11 on 2023-03-07 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Generic_Alphabetic',
            fields=[
                ('generic_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=255, unique=True)),
                ('open_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('order_total', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('brand_name', models.CharField(max_length=150, null=True)),
                ('generic_name', models.CharField(blank=True, max_length=150, null=True)),
                ('brand_description', models.CharField(max_length=150, unique=True)),
                ('brand_description_slug', models.CharField(max_length=150, null=True)),
                ('department', models.CharField(max_length=15, null=True)),
                ('dosage_form', models.CharField(blank=True, max_length=20, null=True)),
                ('unit', models.CharField(max_length=30)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_cost', models.FloatField(null=True)),
                ('quantity_left', models.IntegerField(null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('full_pack_quantity', models.CharField(max_length=10)),
                ('unit_quantity', models.CharField(default=1, max_length=10)),
                ('disabled_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('selected_unit', models.CharField(max_length=30)),
                ('quantity_ordered', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('cost', models.FloatField(default=0)),
                ('unit_quantity', models.CharField(max_length=10)),
                ('full_pack_quantity', models.IntegerField()),
                ('raw_cost', models.FloatField(default=0)),
                ('unit', models.CharField(max_length=30)),
                ('total', models.FloatField()),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_products',
            field=models.ManyToManyField(blank=True, related_name='order_items_field', to='order.OrderProduct'),
        ),
    ]
