# Generated by Django 3.2.11 on 2022-06-26 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_Alphabetic',
            fields=[
                ('brand_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('a', models.BooleanField(default=False)),
                ('b', models.BooleanField(default=False)),
                ('c', models.BooleanField(default=False)),
                ('d', models.BooleanField(default=False)),
                ('e', models.BooleanField(default=False)),
                ('f', models.BooleanField(default=False)),
                ('g', models.BooleanField(default=False)),
                ('h', models.BooleanField(default=False)),
                ('i', models.BooleanField(default=False)),
                ('j', models.BooleanField(default=False)),
                ('k', models.BooleanField(default=False)),
                ('l', models.BooleanField(default=False)),
                ('m', models.BooleanField(default=False)),
                ('n', models.BooleanField(default=False)),
                ('o', models.BooleanField(default=False)),
                ('p', models.BooleanField(default=False)),
                ('q', models.BooleanField(default=False)),
                ('r', models.BooleanField(default=False)),
                ('s', models.BooleanField(default=False)),
                ('t', models.BooleanField(default=False)),
                ('u', models.BooleanField(default=False)),
                ('v', models.BooleanField(default=False)),
                ('w', models.BooleanField(default=False)),
                ('x', models.BooleanField(default=False)),
                ('y', models.BooleanField(default=False)),
                ('z', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Generic_Alphabetic',
            fields=[
                ('generic_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('a', models.BooleanField(default=False)),
                ('b', models.BooleanField(default=False)),
                ('c', models.BooleanField(default=False)),
                ('d', models.BooleanField(default=False)),
                ('e', models.BooleanField(default=False)),
                ('f', models.BooleanField(default=False)),
                ('g', models.BooleanField(default=False)),
                ('h', models.BooleanField(default=False)),
                ('i', models.BooleanField(default=False)),
                ('j', models.BooleanField(default=False)),
                ('k', models.BooleanField(default=False)),
                ('l', models.BooleanField(default=False)),
                ('m', models.BooleanField(default=False)),
                ('n', models.BooleanField(default=False)),
                ('o', models.BooleanField(default=False)),
                ('p', models.BooleanField(default=False)),
                ('q', models.BooleanField(default=False)),
                ('r', models.BooleanField(default=False)),
                ('s', models.BooleanField(default=False)),
                ('t', models.BooleanField(default=False)),
                ('u', models.BooleanField(default=False)),
                ('v', models.BooleanField(default=False)),
                ('w', models.BooleanField(default=False)),
                ('x', models.BooleanField(default=False)),
                ('y', models.BooleanField(default=False)),
                ('z', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer_email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('open_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=50)),
                ('generic_name', models.CharField(max_length=50, null=True)),
                ('brand_description', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=15, null=True)),
                ('dosage_form', models.CharField(max_length=20, null=True)),
                ('presentation', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=15, null=True)),
                ('price', models.FloatField(null=True)),
                ('quantity_left', models.IntegerField(null=True)),
                ('company', models.CharField(max_length=50, null=True)),
                ('full_pack_quantity', models.CharField(max_length=4, null=True)),
                ('unit_quantity', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation', models.CharField(max_length=30)),
                ('brand_name', models.CharField(max_length=50)),
                ('generic_name', models.CharField(max_length=50)),
                ('quantity_ordered', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_items_field', to='order.OrderProduct'),
        ),
    ]
