# Generated by Django 3.2.11 on 2022-10-08 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='disabled_status',
        ),
    ]
