# Generated by Django 3.2.11 on 2022-08-20 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='total_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='raw_cost',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='full_pack_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='unit_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='disabled_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.product'),
        ),
    ]
