# Generated by Django 3.2.11 on 2022-06-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_pack_quantity',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_quantity',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
