# Generated by Django 3.2.11 on 2022-10-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_product_disabled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disabled_status',
            field=models.BooleanField(default=False),
        ),
    ]
