# Generated by Django 3.2.11 on 2022-08-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220820_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='brand_name',
            new_name='brand_description',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product',
            new_name='product_id',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='generic_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
