# Generated by Django 3.2.11 on 2023-03-07 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_product_disabled_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='disabled_status',
        ),
    ]
