# Generated by Django 3.2.11 on 2022-06-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220627_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(blank=True, related_name='order_items_field', to='order.OrderProduct'),
        ),
    ]
