# Generated by Django 3.2.11 on 2022-10-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_product_disabled_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='disabled_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
