# Generated by Django 3.2.11 on 2022-08-20 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220820_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
