# Generated by Django 3.2.11 on 2022-08-20 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderproduct_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
    ]
