# Generated by Django 3.2.11 on 2022-06-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='generic_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
