# Generated by Django 3.2.11 on 2022-08-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20220821_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='presentation',
            new_name='selected_unit',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='presentation',
            new_name='unit',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='raw_cost',
            field=models.FloatField(null=True),
        ),
    ]
