# Generated by Django 3.2.11 on 2022-06-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20220627_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='presentation',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
