# Generated by Django 3.2.11 on 2022-06-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_product_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
