# Generated by Django 3.2.11 on 2022-06-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20220627_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='a',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='b',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='c',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='d',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='e',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='f',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='g',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='h',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='i',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='j',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='k',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='l',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='m',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='n',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='o',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='p',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='q',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='r',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='s',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='t',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='u',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='v',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='w',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='x',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='y',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brand_alphabetic',
            name='z',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='a',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='b',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='c',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='d',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='e',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='f',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='g',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='h',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='i',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='j',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='k',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='l',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='m',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='n',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='o',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='p',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='q',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='r',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='s',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='t',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='u',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='v',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='w',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='x',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='y',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generic_alphabetic',
            name='z',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
