# Generated by Django 3.2.11 on 2022-06-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20220627_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand_alphabetic',
            old_name='brand_name',
            new_name='brand_description',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
