# Generated by Django 3.2.11 on 2022-08-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orderproduct_unit_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
