# Generated by Django 3.2.11 on 2022-08-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_description_slug',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
