# Generated by Django 3.2.11 on 2022-06-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20220628_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
