# Generated by Django 3.2.11 on 2022-09-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_product_brand_description_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='extra_info',
            field=models.TextField(null=True),
        ),
    ]
