# Generated by Django 3.2.11 on 2022-09-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_orderproduct_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
