# Generated by Django 3.2.11 on 2022-07-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_product_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_items',
            new_name='order_products',
        ),
        migrations.AddField(
            model_name='brand_alphabetic',
            name='other',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='generic_alphabetic',
            name='other',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='serial',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='total_cost',
            field=models.FloatField(null=True),
        ),
    ]
