# Generated by Django 3.2.11 on 2022-09-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_orderproduct_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='brand_description',
            field=models.CharField(max_length=150),
        ),
    ]
