# Generated by Django 3.2.11 on 2022-07-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20220703_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand_alphabetic',
            name='b',
        ),
        migrations.AddField(
            model_name='brand_alphabetic',
            name='b_col',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
