# Generated by Django 3.2.11 on 2022-07-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20220704_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand_alphabetic',
            old_name='b_col',
            new_name='b',
        ),
    ]
