# Generated by Django 3.2.11 on 2022-09-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20220929_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='raw_unit',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
