# Generated by Django 3.2.11 on 2022-07-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_rename_b_col_brand_alphabetic_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_letter_brand',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='first_letter_generic',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
