# Generated by Django 3.2.11 on 2022-09-30 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_orderproduct_raw_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='raw_unit',
            new_name='unit',
        ),
    ]
